[book]
authors = ["Théophile Choutri"]
language = "en"
multilingual = false
src = ".markdown"
title = "PG-Entity Book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/tchoutri/pg-entity/tree/main/docs"
