site_name: pg-entity
site_url: https://tchoutri.github.io/pg-entity
docs_dir: 'src'
theme:
  name: material
  palette:
    scheme: preference
    primary: deep-purple
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
