name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.4.0.0"]
        ghc:
          - "8.10.4"

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Prepare environment
      run: |
        mkdir -p $HOME/.local/bin
        sudo apt-get update && sudo apt install -y postgresql-10 libpq-dev 
        echo "/usr/lib/postgresql/10/bin" >> $GITHUB_PATH
        echo "$HOME/.ghcup/bin" >> $GITHUB_PATH
        echo "HOME/.cabal/bin" >> $GITHUB_PATH
        echo "HOME/.local/bin" >> $GITHUB_PATH

    - name: Install cabal-extras
      run: |
        wget https://github.com/phadej/cabal-extras/releases/download/cabal-docspec-0.0.0.20210111/cabal-docspec-0.0.0.20210111.xz -O ./cabal-docspec.xz
        ls -lah
        unxz ./cabal-docspec.xz
        mv cabal-docspec $HOME/.local/bin
        chmod +x $HOME/.local/bin/cabal-docspec

    - name: Freeze
      run: |
        cabal freeze
 
    - uses: actions/cache@v2
      name: Cache ~/.cabal/store and .ghcup
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          .ghcup
        key: ${{ runner.os }}

    - name: Build
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct --disable-optimization
        cabal build -j all

    - name: Docspecs
      run: |
        $HOME/.local/bin/cabal-docspec

    - name: Test
      run: cabal test all
